apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sp6r
  name: sp6r
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sp6r
  type: NodePort
status:
  loadBalancer: {}
